### ISSUE TITLE
"Git Cheat Sheet" link is broken

### ISSUE THREAD

**Issue by svenux** [AdobeDocs/experience-manager-cloud-manager.en#12]
Issue in help/using/configure-your-release-branches.md

The "Git Cheat Sheet" link is broken.
Maybe the correct URL is: [https://github.github.com/training-kit/downloads/github-git-cheat-sheet.pdf](https://github.github.com/training-kit/downloads/github-git-cheat-sheet.pdf)

Please verify and correct the link. Thanks

**Comment by jyotikas** [comment]
Thank you for reporting the issue. I have updated the link on the page.
