### ISSUE TITLE
Title for this page when shared in Slack is Activating Maven Profiles

### ISSUE THREAD

**Issue by justinedelson** [AdobeDocs/experience-manager-cloud-manager.en#17]
Issue in help/using/activating-maven-project.md

https://docs.adobe.com/content/help/en/experience-manager-cloud-manager/using/managing-code/activating-maven-project.html

![image](https://user-images.githubusercontent.com/65906/82049722-d31d8c80-9684-11ea-9a7e-bc6612232ef1.png)

**Comment by jyotikas** [comment]
@justinedelson thank you reporting.
I fixed the issue.
