### ISSUE TITLE
Include Notes about adding Profiles & Users separately on publish instance(s)

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-cloud-manager.en#22]
Issue in help/using/setting-up-users-and-roles.md

This doc just mentions about adding Profiles & Users for Cloud Manager.

Please include a Note in this doc, that states that adding a User or a Profile to the author environment won't create/setup the same user/profile for publish environment.
Separate users/profiles will have to be setup/created for publish environments, depending upon the use case.

[Logged by AEM Support]

**Comment by bohnertchris** [comment]
Thank you for the suggestion, @sukohli. We will review.

CQDOC-16333

**Comment by justinedelson** [comment]
This seems like more of an issue for the AEM Security documentation than the Cloud Manager documentation.

**Comment by sukohli** [comment]
Thanks, @justinedelson 
The doc that you shared with me is helpful. :)

_Doc: https://docs.adobe.com/content/help/en/experience-manager-cloud-service/security/ims-support.html#accessing-instance-cloud-service_
