### ISSUE TITLE
Password-Protected Maven Repository Support does not give details about allowed server ids

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/experience-manager-cloud-manager.en#25]
Issue in help/using/create-an-application-project.md
It just states 

> When the Cloud Manager build process starts, the <servers> element in this file will be merged into the default settings.xml file provided by Cloud Manager

It is crucial to know which server ids are already taken by the default settings.xml and whether certain ids are processed via a mirror.

**Comment by justinedelson** [comment]
Agreed -- I created #26 to add some language about "reserved" server ids.

@kwin I don't fully understand what you mean about mirrors and how it is related. Are you looking for some language that says that we will *never* define a mirror for `*` but only:

* `central`
* `adobe-*`
* `cloud-manager-*`

? But I'm guessing that this is really the concern -- you want some guarantee that Cloud Manager will never try to mirror a custom repository (`myco-repository` in the example).

**Comment by kwin** [comment]
> you want some guarantee that Cloud Manager will never try to mirror a custom repository (myco-repository in the example)

Exactly, thanks for the prompt PR.

**Comment by justinedelson** [comment]
OK. Created https://github.com/AdobeDocs/experience-manager-cloud-manager.en/pull/27 for the mirror language.

**Comment by bohnertchris** [comment]
Great collaboration on this. Thanks for the PR, @justinedelson. Since that seemed to solve the issue, I am closing this.
