### ISSUE TITLE
Lack of whitespace between "Git" and "Repository"

### ISSUE THREAD

**Issue by justinedelson** [AdobeDocs/experience-manager-cloud-manager.en#3]
Issue in help/using/dispatcher-configurations.md

It looks correct in the Markdown, but when rendered on https://docs.adobe.com/content/help/en/experience-manager-cloud-manager/using/getting-started/dispatcher-configurations.html it is all one word:

![image](https://user-images.githubusercontent.com/65906/53978634-b2999000-40d9-11e9-9ec5-dec6655b67ad.png)

**Comment by bbringhu** [comment]
I changed `**Git** **Repository**` to `**Git Repository**`. The space should appear now. fyi @mblawrence

**Comment by justinedelson** [comment]
@bbringhu sorry, missed your response. This did not fix the problem, unfortunately.

![image](https://user-images.githubusercontent.com/65906/57323132-302a4e00-70d3-11e9-9d4c-e796016d3ab7.png)

**Comment by bbringhu** [comment]
I'm not sure what's causing the space to be removed in the note, so I replaced the space with `&nbsp;`. That workaround resolved the issue.

Thanks.

**Comment by justinedelson** [comment]
Looks good now!
