### ISSUE TITLE
Existing docs for Cloud Manager notification setup refers to the old UI

### ISSUE THREAD

**Issue by hamid-k50** [AdobeDocs/experience-manager-cloud-manager.en#30]
Issue in help/using/notifications.md
It looks like the experience cloud manager preferences page UI for setting up email notification has been changed significantly and that's not reflected in the Cloud Manager docs:

https://docs.adobe.com/content/help/en/experience-manager-cloud-manager/using/how-to-use/notifications.html

[submitted by support]

**Comment by aheim0** [comment]
Thank you for raising this, we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-16790

**Comment by bohnertchris** [comment]
This was corrected with commit 3c324a0 to this repo and commit 18d8a81 to the AEMaaCS repo.
