### ISSUE TITLE
Add reference to how to set up API

### ISSUE THREAD

**Issue by andrewmkhoury** [AdobeDocs/experience-manager-cloud-manager.en#32]
Update "Environment Variable" info on [this page](https://github.com/AdobeDocs/experience-manager-cloud-manager.en/blob/master/help/using/build-environment-details.md) with a note.

Update with a note and links referring how to configure the https://github.com/adobe/aio-cli-plugin-cloudmanager to set pipeline variables.

Docs for api integration:
https://www.adobe.io/apis/experiencecloud/cloud-manager/docs.html#!AdobeDocs/cloudmanager-api-docs/master/create-api-integration.md
https://www.adobe.io/apis/experiencecloud/cloud-manager/docs.html#!AdobeDocs/cloudmanager-api-docs/master/permissions.md

**Comment by bohnertchris** [comment]
Thank you for the suggestion, @andrewmkhoury . We will review.

**Comment by bohnertchris** [comment]
CQDOC-16893

**Comment by guillaumecarlino** [comment]
Closing as CQDOC-16893 is closed.
