### ISSUE TITLE
New FAQ Page for Cloud Manager

### ISSUE THREAD

**Issue by andrewmkhoury** [AdobeDocs/experience-manager-cloud-manager.en#34]
I would like to have the content on this page migrated to the official docs and start a new FAQ page for Cloud Manager:
https://helpx.adobe.com/experience-manager/kb/cm/cm-faq.html

**Comment by bohnertchris** [comment]
Thank you for the suggestion, @andrewmkhoury . Can you please specify which page you wish migrated so that we may consider it?

**Comment by bohnertchris** [comment]
Apologies, @andrewmkhoury, I misunderstood your comment. We will review the request. Thanks for the suggestion.

CQDOC-16890

**Comment by bohnertchris** [comment]
Apologies, @andrewmkhoury, but we integrated your suggestions over one year ago and neglected to inform you of the improvement. Thank you for your suggestion!

https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/using-cloud-manager/cloud-manager-cs-faqs.html
https://experienceleague.adobe.com/docs/experience-manager-cloud-manager/content/overview/faqs.html
