### ISSUE TITLE
"Cloud Service Compatibility" is not defined on this document.

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-cloud-manager.en#36]
Issue in help/using/custom-code-quality-rules.md

"Cloud Service Compatibility" is not defined, nor even mentioned, on this document. This is the destination doc page for https://docs.adobe.com/content/help/en/experience-manager-cloud-manager/using/how-to-use/understand-your-test-results.html which  has the note:

"To learn more about the custom code quality rules executed by Cloud Manager, please refer to Custom Code Quality Rules ."

which leads to this page but "Cloud Service Compatibility" is not here.

**Comment by aheim0** [comment]
Thank you for raising this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17000.

**Comment by jyotikas** [comment]
@johnb4 , the updates are now reflected on the page:
https://docs.adobe.com/content/help/en/experience-manager-cloud-manager/using/how-to-use/custom-code-quality-rules.html
