### ISSUE TITLE
Update public documentation Intro page to reflect CM business ownership correctly

### ISSUE THREAD

**Issue by dbalescu** [AdobeDocs/experience-manager-cloud-manager.en#38]
The first line of Intro page from CM public documentation (https://experienceleague.adobe.com/docs/experience-manager-cloud-manager/using/introduction-to-cloud-manager.html?lang=en#introduction-to-cloud-manager) states:
"Cloud Manager, part of the Adobe Managed Services"

The sentence should be changed to reflect the updated business ownership of CM product.

**Comment by TylerRush** [comment]
CQDOC-17131

**Comment by jyotikas** [comment]
Thank you @dbalescu for the feedback.
The updates are now reflected in the Introduction to Cloud Manager page:
https://experienceleague.adobe.com/docs/experience-manager-cloud-manager/using/introduction-to-cloud-manager.html?lang=en
