### ISSUE TITLE
Dispatcher cache flush for non prod deployment should be explicitly called out

### ISSUE THREAD

**Issue by himanshu-pathak** [AdobeDocs/experience-manager-cloud-manager.en#39]
Issue in ./help/using/deploying-code.md

Recently learned that the dispatcher cache is not flushed on non production deployment and should be taken care manually either by ssh access or re-replicating pages. Though it would make sense to completely wipe out cache on non production environments, it should be called out in the documentation if not possible for any reason.

**Comment by anujkapo** [comment]
Thanks, @himanshu-pathak for reporting the issue. We will look into it.

**Comment by anujkapo** [comment]
Tracked using CQDOC-17207.
