### ISSUE TITLE
Environment Variable for Git Commit ID

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/experience-manager-cloud-manager.en#40]
Issue in ./help/using/build-environment-details.md

In the Cloud Manager build we would like to use the commit id (to include it in the bundle and package description). In Jenkins this is provided via environment variables exposed by the Git Plugin (https://plugins.jenkins.io/git/#commit-variables). Is there an environment variable provided in the Cloud Manager build pipeline or do I have to leverage a dedicated plugin like https://github.com/git-commit-id/git-commit-id-maven-plugin?

**Comment by aheim0** [comment]
Thank you for raising this, we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17259.

**Comment by guillaumecarlino** [comment]
Closing this issue as CQDOC-17259 was closed.
Please create a new issue if this is a mistake.

**Comment by kwin** [comment]
Please let the reporter close the issue. This is not fixed at all. I created https://github.com/AdobeDocs/experience-manager-cloud-manager.en/issues/62 as followup.

**Comment by bohnertchris** [comment]
@kwin, engineering is aware of the usefulness of exposing such a variable, but there is none available at this time and I have no outlook to provide when such a variable may become available.
