### ISSUE TITLE
[Content Sensitivity] Branch names displayed in screen shot contain potentially sensitive content

### ISSUE THREAD

**Issue by GuillaumeCleme** [AdobeDocs/experience-manager-cloud-manager.en#41]
Issue in ./help/using/configuring-pipeline.md

In light of recent movements (e.g. Black Lives Matter) that impacted the use of certain technical terms such as `master`, consideration should be given to updating the documentation screenshot below to avoid negative connotations. 

![image](https://user-images.githubusercontent.com/11822651/103559080-90166080-4e83-11eb-9ba6-45856b94a6bc.png)

**Comment by anujkapo** [comment]
Thanks, @GuillaumeCleme. We will take a look.

**Comment by anujkapo** [comment]
Tracked using CQDOC-17270.

**Comment by guillaumecarlino** [comment]
Closing as this was apparently fixed.
