### ISSUE TITLE
Description of Program should be more detailed

### ISSUE THREAD

**Issue by jpritchard** [AdobeDocs/experience-manager-cloud-manager.en#42]
Issue in ./help/using/first-time-login.md

The new video introducing programs appears to be centred around Cloud Service, which gives the impression that it is a button-click away from creating a new Program. However, in AMS the Program is not tied just to a logical infrastructure but in-effect a physical infrastructure. Could we attempt to enhance the clarity here? It creates an idea that the number of Programs on AMS is elastic which is not strictly the case. Thank you.

**Comment by aheim0** [comment]
Thanks for highlighting this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17356.

**Comment by bohnertchris** [comment]
@jpritchard, I appreciate the suggestion, but am not sure to what video you are referring. /help/using/first-time-login.md does not have any videos included in its content. Could you please tell me how you come upon this video? Thank you.

**Comment by bohnertchris** [comment]
I am closing this issue since I am unclear where I need to make any change. If the problem persists, please create a new issue.
