### ISSUE TITLE
Screenshots are out of date. Likely content also

### ISSUE THREAD

**Issue by mattlaun** [AdobeDocs/experience-manager-cloud-manager.en#48]
Issue in ./help/using/configuring-pipeline.md

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
Closing this issue as CQDOC-18136 was closed from lack of details.
Please create a new issue with more details of what should be changed if something is still required.
