### ISSUE TITLE
Method for setting notifications in Cloud Manager doesn't match current UI.

### ISSUE THREAD

**Issue by mattlaun** [AdobeDocs/experience-manager-cloud-manager.en#49]
Issue in ./help/using/notifications.md

Don't know how to control the email notifications separate from the status bar notifications.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This has been documented here.

https://experienceleague.adobe.com/docs/experience-manager-cloud-manager/content/using/notifications.html?#email-notifications
