### ISSUE TITLE
Edit a program name

### ISSUE THREAD

**Issue by clatimier** [AdobeDocs/experience-manager-cloud-manager.en#54]
Issue in ./help/using/setting-up-program.md

With the release 2021.06 customers have the option to edit the name of program via CM UI, see Shankari release email
"Cloud Service customers can now edit the Program name after it has been created by using the Edit Program workflow"

Also https://jira.corp.adobe.com/browse/CMGR-16969

In the documentation page, there is no mention of this feature, and the screenshot in the "Editing a program" section shows the program name as disabled
Could this screenshot amended and the information about the name modification being possible added? 

[Logged by Support]

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
We don't call out explicitly that the name can be edited, but we make it clear that basically all details of the program can be edited after creation.

https://experienceleague.adobe.com/docs/experience-manager-cloud-manager/content/getting-started/program-setup.html?#editing-program
