### ISSUE TITLE
Broken links on critical AEM issues

### ISSUE THREAD

**Issue by shajiahmed** [AdobeDocs/experience-manager-cloud-manager.en#55]
I see lot of broken links on 
https://experienceleague.adobe.com/docs/experience-cloud-kcs/kbarticles/KA-17457.html?lang=en
specially any text with [this article]

**Comment by aheim0** [comment]
Thanks for raising this. This page is not under the jurisdiction of our team, but we will investigate and contact the appropriate team (might take a while though).

**Comment by aheim0** [comment]
https://experienceleague.adobe.com/docs/experience-cloud-kcs/kbarticles/KA-17457.html?lang=en

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
This ticket has been reassigned. If you want/need more information please open a new ticket against the experience-cloud-kcs repo.
Closing this issue.

**Comment by aheim0** [comment]
I have just received notification that the links have been updated. Hope that helps.
