### ISSUE TITLE
Cache Invalidate vs flush backwards

### ISSUE THREAD

**Issue by Brohio-Babes** [AdobeDocs/experience-manager-cloud-manager.en#56]
https://experienceleague.adobe.com/docs/experience-manager-cloud-manager/using/how-to-use/pipelines/configuring-production-pipelines.html?lang=en

Incorrect in public docs:
Flush - Perform a cache invalidation, similar to when content is activated from an authoring instance to a publishing instance.
Invalidate - Performs a cache deletion.

What it should be:
Flush - Performs a cache deletion.
Invalidate - Perform a cache invalidation, similar to when content is activated from an authoring instance to a publishing instance.

**Comment by Brohio-Babes** [comment]
PR: https://github.com/AdobeDocs/experience-manager-cloud-manager.en/pull/57

**Comment by aheim0** [comment]
Thanks for raising this - will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
Closing.  The issue should be fixed now.
