### ISSUE TITLE
feature request: rss feed 

### ISSUE THREAD

**Issue by thedevopsguyblog** [AdobeDocs/experience-manager-cloud-manager.en#58]
It would be a good feature to subscribe to CM release notes via RSS.

**Comment by aheim0** [comment]
Thanks for raising this - we will review.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
This is outside our scope, but I have passed the issue onto the appropriate team.
Closing issue now.
