### ISSUE TITLE
profiles

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-manager.en#60]
Issue in ./help/requirements/users-and-roles.md
The document says:
You can create or add users/groups to these product profiles with the Admin Console.
Log in to the Admin Console and click New Profile to add a new profile.

When I go to adminconsole.adobe.com, I don't see a "New Profile" link/button. I have no idea how to get to the page shown in the doc.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thank you for raising this, @alisonasanchez. We'll add the missing steps.

**Comment by bohnertchris** [comment]
This was corrected with commit 55ad91f.
