### ISSUE TITLE
Environment Variable for Git Commit (#2)

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/experience-manager-cloud-manager.en#62]
As follow up to https://github.com/AdobeDocs/experience-manager-cloud-manager.en/issues/40 which has been closed without explanation.
I still don't see an environment variable which exposes the git commit in https://experienceleague.adobe.com/docs/experience-manager-cloud-manager/content/getting-started/project-creation/build-environment.html?lang=en#environment-variables. Please clarify why #40 has been closed and what has been fixed actually.

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
@kwin, sorry I had to close #40. It looks like our internal issue associated with it was mistakenly closed. Thanks for creating this new issue. We'll have a look.

**Comment by bohnertchris** [comment]
Sorry for the confusion on our part, @kwin. We were performing some end-of-year auditing of our GitHub issues and our internal system indicated that #40 was complete and therefore we closed it. This was a mistake. Thank you for reopening.

**Comment by bohnertchris** [comment]
@kwin, engineering is aware of the usefulness of exposing such a variable, but there is none available at this time and I have no outlook to provide when such a variable may become available.
