### ISSUE TITLE
Provide SonarQube rules so they can be imported

### ISSUE THREAD

**Issue by nhirrle** [AdobeDocs/experience-manager-cloud-manager.en#63]
Within our projects a typical step is a sonar scan before pushing code into an adobe git.  Right now we use standard Sonar rules but not the ones specific for AEM. We would like to reuse the ones which Cloud manager uses: https://experienceleague.adobe.com/docs/experience-manager-cloud-manager/content/using/custom-code-quality-rules.html?lang=en

Could you please export the rules so we can integrate them within our own sonarqube?

**Comment by anujkapo** [comment]
Thanks, @nhirrle for the enhancement request. We'll look into it.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
The SonarQube rules contain Adobe proprietary information and unfortunately can not be provided. We have updated the documentation to clarify this. See commit 256fc4f to this repository and commit e459a8f to the AEM as a Cloud Service repository.

https://experienceleague.adobe.com/docs/experience-manager-cloud-manager/content/using/custom-code-quality-rules.html
https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/using-cloud-manager/test-results/custom-code-quality-rules.html
