### ISSUE TITLE
Deleting and Recreating repositories

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-manager.en#64]
Issue in ./help/managing-code/repositories.md
The following note should be added to the documentation:

When a repository is deleted in cloud manager, it is only soft deleted, meaning it is kept, but marked as deleted for recovery purposes. If the user tries to recreate one with the same name, the user will get an error saying "An error has occurred while trying to create repository. Please contact your CSE or Adobe Support." If this error is received, please log a ticket with support so that the cloud manager team can rename the archived project, or use a different name.

Label: DocBugBlitz2023

**Comment by bohnertchris** [comment]
Thanks for providing this detail, @alisonasanchez. We will have a look.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This has been fixed in commit cbaacd7.
