### ISSUE TITLE
Link is needed

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-manager.en#67]
Issue in ./help/getting-started/first-time-login.md
Can you add a link for this:
Log in to Adobe Experience Cloud and you see the list of programs.

So the user knows how to access "Adobe Experience Cloud".

Label: DocBugBlitz2023

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This was completed with commit 01f066e.
