### ISSUE TITLE
Cross Link to AEM as a Cloud Service missing

### ISSUE THREAD

**Issue by ackoch** [AdobeDocs/experience-manager-cloud-manager.en#69]
Issue in ./help/requirements/role-based-permissions.md

Other documentation pages where AEM/AMS and AEM/CS have differences have a link to the according other page. In this case

https://experienceleague.adobe.com/docs/experience-manager-cloud-manager/content/requirements/role-based-permissions.html?lang=en

and 

https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/onboarding/concepts/cloud-manager-introduction.html

could be interlinked. 

The issue is.. whenever I google for "Cloud Manager Permissions" I'll end up on this page .. and the other is nowhere to be found..

**Comment by raimanS** [comment]
Thank you for reporting this issue. We will investigate.

**Comment by raimanS** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thank you for the suggestion. A link has been added to the page as part of commit c427533.
