### ISSUE TITLE
Information about OS

### ISSUE THREAD

**Issue by jbaix** [AdobeDocs/experience-manager-cloud-manager.en#8]
Issue in help/using/manage-your-environment.md

Just in case the customer wants to set up their own development environment on premise, it should be interesting to include the OS used in Managed Services, to configure the DEV env as close as possible to PRE-PROD.

Thank you.

**Comment by jyotikas** [comment]
@jbaix thank you for your comment. We are looking into this issue and will respond soon.

**Comment by bohnertchris** [comment]
CQDOC-15606

**Comment by justinedelson** [comment]
I don't think this relates to Cloud Manager specifically. This is a general AMS question.

**Comment by jyotikas** [comment]
Thank you for reporting @jbaix.
Please feel free to reopen the issue. No updates required for Cloud Manager.
