### ISSUE TITLE
Add SonarQube Concepts link

### ISSUE THREAD

**Issue by bolond2** [AdobeDocs/experience-manager-cloud-manager.en#9]
Issue in help/using/understand-your-test-results.md
Need to add documentation around SonarQube concepts from this - https://docs.sonarqube.org/7.4/user-guide/concepts/
Suggestion from Justin Edelson after posing the question from a customer.

**Comment by bohnertchris** [comment]
Thank you for the suggestion, @bolond2 . We will review the suggested material.

**Comment by bohnertchris** [comment]
CQDOC-15607

**Comment by guillaumecarlino** [comment]
Closing, this was fixed.
